use windows::Win32::UI::Input::KeyboardAndMouse::{
  VK_0, VK_1, VK_2, VK_3, VK_4, VK_5, VK_6, VK_7, VK_8, VK_9, VK_A, VK_ADD, VK_APPS, VK_B, VK_BACK, VK_C, VK_CAPITAL,
  VK_D, VK_DECIMAL, VK_DELETE, VK_DIVIDE, VK_DOWN, VK_E, VK_END, VK_ESCAPE, VK_F, VK_F1, VK_F10, VK_F11, VK_F12, VK_F2,
  VK_F3, VK_F4, VK_F5, VK_F6, VK_F7, VK_F8, VK_F9, VK_G, VK_H, VK_HOME, VK_I, VK_INSERT, VK_J, VK_K, VK_L, VK_LEFT,
  VK_M, VK_MULTIPLY, VK_N, VK_NEXT, VK_NUMLOCK, VK_NUMPAD0, VK_NUMPAD1, VK_NUMPAD2, VK_NUMPAD3, VK_NUMPAD4, VK_NUMPAD5,
  VK_NUMPAD6, VK_NUMPAD7, VK_NUMPAD8, VK_NUMPAD9, VK_O, VK_OEM_COMMA, VK_OEM_MINUS, VK_OEM_PERIOD, VK_OEM_PLUS, VK_P,
  VK_PAUSE, VK_PRIOR, VK_Q, VK_R, VK_RETURN, VK_RIGHT, VK_S, VK_SCROLL, VK_SNAPSHOT, VK_SPACE, VK_SUBTRACT, VK_T,
  VK_TAB, VK_U, VK_UP, VK_V, VK_VOLUME_DOWN, VK_VOLUME_MUTE, VK_VOLUME_UP, VK_W, VK_X, VK_Y, VK_Z,
};

#[derive(Debug, Clone, Copy)]
#[repr(u16)]
pub enum KeyboardKey {
  Backspace = VK_BACK.0,
  Tab = VK_TAB.0,
  Return = VK_RETURN.0,
  Pause = VK_PAUSE.0,
  CapsLock = VK_CAPITAL.0,
  Esc = VK_ESCAPE.0,
  Space = VK_SPACE.0,
  PgUp = VK_PRIOR.0,
  PgDown = VK_NEXT.0,
  End = VK_END.0,
  Home = VK_HOME.0,
  LeftArrow = VK_LEFT.0,
  UpArrow = VK_UP.0,
  RightArrow = VK_RIGHT.0,
  DownArrow = VK_DOWN.0,
  PrintScreen = VK_SNAPSHOT.0,
  Insert = VK_INSERT.0,
  Delete = VK_DELETE.0,
  Number0 = VK_0.0,
  Number1 = VK_1.0,
  Number2 = VK_2.0,
  Number3 = VK_3.0,
  Number4 = VK_4.0,
  Number5 = VK_5.0,
  Number6 = VK_6.0,
  Number7 = VK_7.0,
  Number8 = VK_8.0,
  Number9 = VK_9.0,
  A = VK_A.0,
  B = VK_B.0,
  C = VK_C.0,
  D = VK_D.0,
  E = VK_E.0,
  F = VK_F.0,
  G = VK_G.0,
  H = VK_H.0,
  I = VK_I.0,
  J = VK_J.0,
  K = VK_K.0,
  L = VK_L.0,
  M = VK_M.0,
  N = VK_N.0,
  O = VK_O.0,
  P = VK_P.0,
  Q = VK_Q.0,
  R = VK_R.0,
  S = VK_S.0,
  T = VK_T.0,
  U = VK_U.0,
  V = VK_V.0,
  W = VK_W.0,
  X = VK_X.0,
  Y = VK_Y.0,
  Z = VK_Z.0,
  Menu = VK_APPS.0,
  Numpad0 = VK_NUMPAD0.0,
  Numpad1 = VK_NUMPAD1.0,
  Numpad2 = VK_NUMPAD2.0,
  Numpad3 = VK_NUMPAD3.0,
  Numpad4 = VK_NUMPAD4.0,
  Numpad5 = VK_NUMPAD5.0,
  Numpad6 = VK_NUMPAD6.0,
  Numpad7 = VK_NUMPAD7.0,
  Numpad8 = VK_NUMPAD8.0,
  Numpad9 = VK_NUMPAD9.0,
  Multiply = VK_MULTIPLY.0,
  Add = VK_ADD.0,
  Subtract = VK_SUBTRACT.0,
  Decimal = VK_DECIMAL.0,
  Divide = VK_DIVIDE.0,
  F1 = VK_F1.0,
  F2 = VK_F2.0,
  F3 = VK_F3.0,
  F4 = VK_F4.0,
  F5 = VK_F5.0,
  F6 = VK_F6.0,
  F7 = VK_F7.0,
  F8 = VK_F8.0,
  F9 = VK_F9.0,
  F10 = VK_F10.0,
  F11 = VK_F11.0,
  F12 = VK_F12.0,
  NumLock = VK_NUMLOCK.0,
  ScrollLock = VK_SCROLL.0,
  VolumeMute = VK_VOLUME_MUTE.0,
  VolumeDown = VK_VOLUME_DOWN.0,
  VolumeUp = VK_VOLUME_UP.0,
  Plus = VK_OEM_PLUS.0,
  Comma = VK_OEM_COMMA.0,
  Minus = VK_OEM_MINUS.0,
  Period = VK_OEM_PERIOD.0,
}
